<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="lidar_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="${chss_len/2 - lidar_rad} 0 ${chss_h + lidar_h/2}" rpy="0 0 ${pi/2 * 0.95}"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder length="${lidar_h}" radius="${lidar_rad}"/>
            </geometry>
            <material name='red'/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${lidar_h}" radius="${lidar_rad}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass='${wheel_mass}' length="${wheel_wid}" radius="${wheel_rad}">
            <origin xyz='0 0 0' rpy='0 0 0'/>
        </xacro:inertial_cylinder>
    </link>
    
    <gazebo reference='laser_frame'>
        <material>Gazebo/Red</material>
        <sensor name="laser" type="ray">
            <pose> 0 0 ${lidar_h_to_cam} 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.15</min>
                    <max>12</max>
                    <resolution>1</resolution>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <frame_name>laser_frame</frame_name>
                <output_type>sensor_msgs/LaserScan</output_type>
            </plugin>
        </sensor>
    </gazebo>

</robot>