<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename='inertial_macros.xacro'/>

    <!-- Base Link -->
    <link name="base_link">
    </link>

    <!-- Chassis -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0"/>
    </joint>
    
    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chss_h/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chss_len} ${chss_wid} ${chss_h}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chss_h/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chss_len} ${chss_wid} ${chss_h}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass='${chss_mass}' x='${chss_len}' y='${chss_wid}' z='${chss_h}'>
            <origin xyz="0 0 ${chss_h/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Right wheel -->
    <joint name='right_wheel_joint' type='continuous'>
        <parent link='base_link'/>
        <child link='right_wheel'/>
        <origin xyz='0 -${wheel_to_origin} 0' rpy='${pi/2} 0 0'/>
        <axis xyz='0 0 -1'/>
    </joint>

    <link name='right_wheel'>
        <visual>
            <geometry>
                <cylinder length="${wheel_wid}" radius="${wheel_rad}"/>
            </geometry>
            <material name='blue'/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_rad}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass='${wheel_mass}' length="${wheel_wid}" radius="${wheel_rad}">
            <origin xyz='0 0 0' rpy='0 0 0'/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference='right_wheel'>
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- Left wheel -->
    <joint name='left_wheel_joint' type='continuous'>
        <parent link='base_link'/>
        <child link='left_wheel'/>
        <origin xyz='0 ${wheel_to_origin} 0' rpy='${-pi/2} 0 0'/>
        <axis xyz='0 0 1'/>
    </joint>

    <link name='left_wheel'>
        <visual>
            <geometry>
                <cylinder length="${wheel_wid}" radius="${wheel_rad}"/>
            </geometry>
            <material name='blue'/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_rad}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass='${wheel_mass}' length="${wheel_wid}" radius="${wheel_rad}">
            <origin xyz='0 0 0' rpy='0 0 0'/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference='left_wheel'>
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- Front Caster wheel -->
    <joint name='front_caster_joint' type='fixed'>
        <parent link='chassis'/>
        <child link='front_caster'/>
        <origin xyz='${front_caster_to_origin} 0 0'/>
    </joint>
    <link name='front_caster'>
        <visual>
            <geometry>
                <sphere radius='${caster_rad}'/>
            </geometry>
            <material name='black'/>
        </visual>
        <collision>
            <geometry>
                <sphere radius='${caster_rad}'/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass='${caster_mass}' radius='${caster_rad}'>
            <origin xyz='0 0 0'/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="front_caster">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- right caster -->
    <joint name='right_caster_joint' type='fixed'>
        <parent link='chassis'/>
        <child link='right_caster'/>
        <origin xyz='${-back_caster_to_x} ${-back_caster_to_y} 0'/>
    </joint>
    <link name='right_caster'>
        <visual>
            <geometry>
                <sphere radius='${caster_rad}'/>
            </geometry>
            <material name='black'/>
        </visual>
        <collision>
            <geometry>
                <sphere radius='${caster_rad}'/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass='${caster_mass}' radius='${caster_rad}'>
            <origin xyz='0 0 0'/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="right_caster">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- left caster -->
    <joint name='left_caster_joint' type='fixed'>
        <parent link='chassis'/>
        <child link='left_caster'/>
        <origin xyz='${-back_caster_to_x} ${back_caster_to_y} 0'/>
    </joint>
    <link name='left_caster'>
        <visual>
            <geometry>
                <sphere radius='${caster_rad}'/>
            </geometry>
            <material name='black'/>
        </visual>
        <collision>
            <geometry>
                <sphere radius='${caster_rad}'/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass='${caster_mass}' radius='${caster_rad}'>
            <origin xyz='0 0 0'/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="left_caster">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>