scan_filter_chain:
  - name: angle_filter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -0.7854  # -45 degrees in radians
      upper_angle: 0.7854     # 45 degrees in radians