scan_filter:
  - name: angle_filter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -1.56  # -45 degrees in radians
      upper_angle: 1.56   # 45 degrees in radians